package com.geriatriccare.integration.api;

import com.geriatriccare.base.BaseIntegrationTest;
import com.geriatriccare.dto.PatientRequest;
import com.geriatriccare.dto.PatientResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.time.LocalDate;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for Alert System (Epic 8 — AlertController).
 *
 * AlertController is READ-ONLY + workflow actions — there is NO POST /api/alerts to create alerts.
 * Alerts are generated by the system (AlertService triggered by AlertRules + VitalSign recordings).
 *
 * AlertController endpoints:
 *   GET  /api/alerts/{id}
 *   GET  /api/alerts/patient/{id}/active
 *   GET  /api/alerts/patient/{id}
 *   GET  /api/alerts/patient/{id}/paginated
 *   GET  /api/alerts/patient/{id}/count
 *   POST /api/alerts/{id}/acknowledge  → ADMIN, PHYSICIAN, CAREGIVER only
 *   POST /api/alerts/{id}/resolve      → ADMIN, PHYSICIAN, CAREGIVER only
 */
@DisplayName("Alert API Integration Tests")
class AlertApiTest extends BaseIntegrationTest {

    private UUID patientId;

    @BeforeEach
    void createTestPatient() {
        PatientRequest req = new PatientRequest();
        req.setFirstName("Alert");
        req.setLastName("TestPatient");
        req.setDateOfBirth(LocalDate.of(1938, 3, 15));

        ResponseEntity<PatientResponse> r = postWithAuth(
            "/api/patients", req, adminToken, PatientResponse.class);
        assertThat(r.getStatusCode()).isEqualTo(HttpStatus.CREATED);
        patientId = r.getBody().getId();
    }

    // ─── List / count endpoints ───────────────────────────────────────────────

    @Test
    @DisplayName("GET /api/alerts/patient/{id}/active → 200 empty list for new patient")
    void getActiveAlerts_newPatient_returnsEmptyList() {
        ResponseEntity<String> response = getWithAuth(
            "/api/alerts/patient/" + patientId + "/active", caregiverToken, String.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).contains("[]");
    }

    @Test
    @DisplayName("GET /api/alerts/patient/{id} → 200 empty list for new patient")
    void getAlertsByPatient_newPatient_returnsEmptyList() {
        ResponseEntity<String> response = getWithAuth(
            "/api/alerts/patient/" + patientId, adminToken, String.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).contains("[]");
    }

    @Test
    @DisplayName("GET /api/alerts/patient/{id}/count → 200 returns 0 for new patient")
    void getActiveAlertCount_newPatient_returnsZero() {
        ResponseEntity<Long> response = getWithAuth(
            "/api/alerts/patient/" + patientId + "/count", physicianToken, Long.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(0L);
    }

    @Test
    @DisplayName("GET /api/alerts/patient/{id}/paginated → 200 with Spring Page structure")
    void getAlertsPaginated_returnsPageResponse() {
        ResponseEntity<String> response = getWithAuth(
            "/api/alerts/patient/" + patientId + "/paginated?page=0&size=10",
            adminToken, String.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).contains("content"); // Spring Page JSON
    }

    @Test
    @DisplayName("GET /api/alerts/{id} → 404 for non-existent alert")
    void getAlert_nonExistent_returns404() {
        assertThat(getWithAuth("/api/alerts/" + UUID.randomUUID(), adminToken, String.class)
            .getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
    }

    // ─── Role access ──────────────────────────────────────────────────────────

    @Test
    @DisplayName("GET /api/alerts/patient/{id}/active → 200 for FAMILY role")
    void getActiveAlerts_asFamily_returns200() {
        assertThat(getWithAuth("/api/alerts/patient/" + patientId + "/active",
            familyToken, String.class).getStatusCode()).isEqualTo(HttpStatus.OK);
    }

    @Test
    @DisplayName("GET /api/alerts/patient/{id}/active → 401 without token")
    void getActiveAlerts_noToken_returns401() {
        assertThat(restTemplate.getForEntity(
            baseUrl + "/api/alerts/patient/" + patientId + "/active", String.class)
            .getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }

    @Test
    @DisplayName("POST /api/alerts/{id}/acknowledge → 403 for FAMILY (not in @PreAuthorize list)")
    void acknowledgeAlert_asFamily_returns403() {
        assertThat(postWithAuth("/api/alerts/" + UUID.randomUUID() + "/acknowledge",
            null, familyToken, String.class).getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
    }

    @Test
    @DisplayName("POST /api/alerts/{id}/resolve → 403 for FAMILY")
    void resolveAlert_asFamily_returns403() {
        assertThat(postWithAuth("/api/alerts/" + UUID.randomUUID() + "/resolve",
            null, familyToken, String.class).getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
    }

    @Test
    @DisplayName("POST /api/alerts/{id}/acknowledge → 404 for non-existent alert (ADMIN)")
    void acknowledgeAlert_nonExistent_returns404() {
        assertThat(postWithAuth("/api/alerts/" + UUID.randomUUID() + "/acknowledge",
            null, adminToken, String.class).getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
    }

    @Test
    @DisplayName("POST /api/alerts/{id}/resolve → 404 for non-existent alert (CAREGIVER)")
    void resolveAlert_nonExistent_returns404() {
        assertThat(postWithAuth("/api/alerts/" + UUID.randomUUID() + "/resolve",
            null, caregiverToken, String.class).getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
    }
}
