spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  
  # Disable Thymeleaf template checking
  thymeleaf:
    check-template-location: false

# JWT Configuration
app:
  jwt:
    secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25UaGF0SXNTZWN1cmVFbm91Z2hGb3JITUFDMjU2QWxnb3JpdGht
    expiration: 86400
  
  # Default Owner User Configuration
  default:
    owner:
      email: owner@geriatriccare.com
      password: Owner123!
      firstName: System
      lastName: Owner

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.geriatriccare: DEBUG
    org.springframework.security: DEBUG