server:
  port: 8080

spring:
  application:
    name: geriatric-home-care-system
  
  datasource:
    url: jdbc:postgresql://ep-soft-sun-adwzcrki-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_iMN4V6rfSawv
    driver-class-name: org.postgresql.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  security:
    jwt:
      secret-key: myVerySecureSecretKeyThatShouldBeAtLeast256BitsLongForHS256Algorithm
      expiration-time: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.geriatriccare: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"